# configs/model_config.yaml
model:
  vocab_size: 30522
  d_model: 512
  n_heads: 8
  n_layers: 6
  d_ff: 2048
  max_seq_length: 512
  dropout: 0.1

tokenizer:
  name: "bert-base-uncased"
  max_length: 512